export const ACTION_NAMES = {
  GET_WISHLIST: {
    GET_PAGINATION: "GET_PAGINATION",
    GET_PAGINATION_SUCCESS: "GET_PAGINATION_SUCCESS",
    GET_PAGINATION_FAILED: "GET_PAGINATION_FAILED",
  },
  ADD_TO_WISHLIST: {
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    ADD_TO_WISHLIST_SUCCESS: "ADD_TO_WISHLIST_SUCCESS",
    ADD_TO_WISHLIST_FAILED: "ADD_TO_WISHLIST_FAILED",
  },
  ADD_TO_CART: {
    ADD_TO_CART: "ADD_TO_CART",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILED: "ADD_TO_CART_FAILED",
  },
  DELETE_WISHLIST_ITEM: {
    DELETE_WISHLIST_ITEM: "DELETE_WISHLIST_ITEM",
    DELETE_WISHLIST_ITEM_SUCCESS: "DELETE_WISHLIST_ITEM_SUCCESS",
    DELETE_WISHLIST_ITEM_FAILED: "DELETE_WISHLIST_ITEM_FAILED",
  },
};
