export const ACTION_NAMES = {
  GET_WISHLIST: {
    GET_PAGINATION: "GET_PAGINATION",
    GET_PAGINATION_SUCCESS: "GET_PAGINATION_SUCCESS",
    GET_PAGINATION_FAILED: "GET_PAGINATION_FAILED",
  },
};
