export const ACTION_NAMES = {
  UPSERT_ATTRIBUTE: {
    UPSERT_ATTRIBUTE: "UPSERT_ATTRIBUTE",
    UPSERT_ATTRIBUTE_SUCCESS: "UPSERT_ATTRIBUTE_SUCCESS",
    UPSERT_ATTRIBUTE_FAIL: "UPSERT_ATTRIBUTE_FAIL",
  },
  GET_PAGINATION: {
    GET_PAGINATION: "GET_PAGINATION",
    GET_PAGINATION_SUCCESS: "GET_PAGINATION_SUCCESS",
    GET_PAGINATION_FAIL: "GET_PAGINATION_FAIL",
  },
  RESET_PAGINATION_TO_RELOAD: {
    RESET_PAGINATION_TO_RELOAD: "RESET_PAGINATION_TO_RELOAD",
  },
  GET_ATTRIBUTES: {
    GET_ATTRIBUTES: "GET_ATTRIBUTES",
    GET_ATTRIBUTES_SUCCESS: "GET_ATTRIBUTES_SUCCESS",
    GET_ATTRIBUTES_FAIL: "GET_ATTRIBUTES_FAIL",
  },
  DELETE: {
    DELETE: "DELETE",
    DELETE_SUCCESS: "DELETE_SUCCESS",
    DELETE_FAIL: "DELETE_FAIL",
  },
};
