export const ACTION_NAMES = {
  CREATE_ATTRIBUTE: {
    CREATE_ATTRIBUTE: "CREATE_ATTRIBUTE",
    CREATE_ATTRIBUTE_SUCCESS: "CREATE_ATTRIBUTE_SUCCESS",
    CREATE_ATTRIBUTE_FAIL: "CREATE_ATTRIBUTE_FAIL",
  },
  GET_PAGINATION: {
    GET_PAGINATION: "GET_PAGINATION",
    GET_PAGINATION_SUCCESS: "GET_PAGINATION_SUCCESS",
    GET_PAGINATION_FAIL: "GET_PAGINATION_FAIL",
  },
  RESET_PAGINATION_TO_RELOAD: {
    RESET_PAGINATION_TO_RELOAD: "RESET_PAGINATION_TO_RELOAD",
  },
  GET_ATTRIBUTES: {
    GET_ATTRIBUTES: "GET_ATTRIBUTES",
    GET_ATTRIBUTES_SUCCESS: "GET_ATTRIBUTES_SUCCESS",
    GET_ATTRIBUTES_FAIL: "GET_ATTRIBUTES_FAIL",
  },
};
