export const ACTION_NAMES = {
    UPSERT_COUPON: {
      UPSERT_COUPON: "UPSERT_COUPON",
      UPSERT_COUPON_SUCCESS: "UPSERT_COUPON_SUCCESS",
      UPSERT_COUPON_FAIL: "UPSERT_COUPON_FAIL",
    },
    GET_PAGINATION: {
      GET_COUPON_PAGINATION: "GET_COUPON_PAGINATION",
      GET_COUPON_PAGINATION_SUCCESS: "GET_COUPON_PAGINATION_SUCCESS",
      GET_COUPON_PAGINATION_FAIL: "GET_COUPON_PAGINATION_FAIL",
    },
    RESET_COUPON_PAGINATION_TO_RELOAD: {
      RESET_COUPON_PAGINATION_TO_RELOAD: "RESET_COUPON_PAGINATION_TO_RELOAD",
    },
    DELETE_COUPON: {
      DELETE_COUPON: "DELETE_COUPON",
      DELETE_COUPON_SUCCESS: "DELETE_COUPON_SUCCESS",
      DELETE_COUPON_FAIL: "DELETE_COUPON_FAIL",
    },
  };
  