export const NAME_ACTIONS = {
  GET_ALL_PROVINCE: {
    GET_ALL_PROVINCE: "GET_ALL_PROVINCE",
    GET_ALL_PROVINCE_SUCCESS: "GET_ALL_PROVINCE_SUCCESS",
    GET_ALL_PROVINCE_FAIL: "GET_ALL_PROVINCE_FAIL",
  },
  GET_DISTRICT_BY_PROVINCE_ID: {
    GET_DISTRICT_BY_PROVINCE_ID: "GET_DISTRICT_BY_PROVINCE_ID",
    GET_DISTRICT_BY_PROVINCE_ID_SUCCESS: "GET_DISTRICT_BY_PROVINCE_ID_SUCCESS",
    GET_DISTRICT_BY_PROVINCE_ID_FAIL: "GET_DISTRICT_BY_PROVINCE_ID_FAIL",
  },
  GET_WARD_BY_DISTRICT_ID: {
    GET_WARD_BY_DISTRICT_ID: "GET_WARD_BY_DISTRICT_ID",
    GET_WARD_BY_DISTRICT_ID_SUCCESS: "GET_WARD_BY_DISTRICT_ID_SUCCESS",
    GET_WARD_BY_DISTRICT_ID_FAIL: "GET_WARD_BY_DISTRICT_ID_FAIL",
  },
  CREATE_ADDRESS: {
    CREATE_ADDRESS: "CREATE_ADDRESS",
    CREATE_ADDRESS_SUCCESS: "CREATE_ADDRESS_SUCCESS",
    CREATE_ADDRESS_FAIL: "CREATE_ADDRESS_FAIL",
  },
  GET_DEFAULT: {
    GET_DEFAULT: "GET_DEFAULT",
    GET_DEFAULT_SUCCESS: "GET_DEFAULT_SUCCESS",
    GET_DEFAULT_FAIL: "GET_DEFAULT_FAIL",
  },
};
