export const NAME_ACTIONS = {
  GET_ALL_PROVINCE: {
    GET_ALL_PROVINCE: "GET_ALL_PROVINCE",
    GET_ALL_PROVINCE_SUCCESS: "GET_ALL_PROVINCE_SUCCESS",
    GET_ALL_PROVINCE_FAIL: "GET_ALL_PROVINCE_FAIL",
  },
  GET_DISTRICT_BY_PROVINCE_ID: {
    GET_DISTRICT_BY_PROVINCE_ID: "GET_DISTRICT_BY_PROVINCE_ID",
    GET_DISTRICT_BY_PROVINCE_ID_SUCCESS: "GET_DISTRICT_BY_PROVINCE_ID_SUCCESS",
    GET_DISTRICT_BY_PROVINCE_ID_FAIL: "GET_DISTRICT_BY_PROVINCE_ID_FAIL",
  },
  GET_WARD_BY_DISTRICT_ID: {
    GET_WARD_BY_DISTRICT_ID: "GET_WARD_BY_DISTRICT_ID",
    GET_WARD_BY_DISTRICT_ID_SUCCESS: "GET_WARD_BY_DISTRICT_ID_SUCCESS",
    GET_WARD_BY_DISTRICT_ID_FAIL: "GET_WARD_BY_DISTRICT_ID_FAIL",
  },
};
