export const NAME_ACTIONS = {
  VERIFY_COUPON: {
    VERIFY_COUPON: "VERIFY_COUPON",
    VERIFY_COUPON_SUCCESS: "VERIFY_COUPON_SUCCESS",
    VERIFY_COUPON_FAIL: "VERIFY_COUPON_FAIL",
  },
  REMOVE_COUPON: {
    REMOVE_COUPON: "REMOVE_COUPON",
  },
  COUPON_HOMEPAGE:{
    GET_COUPON_HOMEPAGE: "GET_COUPON_HOMEPAGE",
    GET_COUPON_HOMEPAGE_SUCCESS: "GET_COUPON_HOMEPAGE_SUCCESS",
    GET_COUPON_HOMEPAGE_FAILED: "GET_COUPON_HOMEPAGE_FAILED"
  },
  COUPON_USER:{
    GET_COUPON_USER: "GET_COUPON_USER",
    GET_COUPON_USER_SUCCESS: "GET_COUPON_USER_SUCCESS",
    GET_COUPON_USER_FAILED: "GET_COUPON_USER_FAILED"
  },
  SAVE_COUPON_USER: {
    SAVE_COUPON_USER : "SAVE_COUPON_USER",
    SAVE_COUPON_USER_SUCCESS: "SAVE_COUPON_USER_SUCCESS",
    SAVE_COUPON_USER_FAILED: "SAVE_COUPON_USER_FAILED"
  },
  USER_APPLY_COUPON: {
    USER_APPLY_COUPON: "USER_APPLY_COUPON",
    USER_APPLY_COUPON_SUCCESS: "USER_APPLY_COUPON_SUCCESS",
    USER_APPLY_COUPON_FAILED: "USER_APPLY_COUPON_FAILD",
  },
  USER_REMOVE_APPLY_COUPON: {
    USER_REMOVE_APPLY_COUPON_SUCCESS: "USER_REMOVE_APPLY_COUPON_SUCCESS"
  }
};
