export const NAME_ACTIONS = {
  VERIFY_COUPON: {
    VERIFY_COUPON: "VERIFY_COUPON",
    VERIFY_COUPON_SUCCESS: "VERIFY_COUPON_SUCCESS",
    VERIFY_COUPON_FAIL: "VERIFY_COUPON_FAIL",
  },
  REMOVE_COUPON: {
    REMOVE_COUPON: "REMOVE_COUPON",
  },
};
