export const ACTION_NAMES = {
  GET_PAGINATION: {
    GET_PAGINATION: "GET_PAGINATION",
    GET_PAGINATION_SUCCESS: "GET_PAGINATION_SUCCESS",
    GET_PAGINATION_FAIL: "GET_PAGINATION_FAIL",
  },
  RESET_PAGINATION_TO_RELOAD: {
    RESET_PAGINATION_TO_RELOAD: "RESET_PAGINATION_TO_RELOAD",
  },
};
