export const ACTION_NAMES = {
  GET_ALL: {
    GET_NOTI_PAGINATION: "GET_NOTI_PAGINATION",
    GET_NOTI_PAGINATION_SUCCESS: "GET_NOTI_PAGINATION_SUCCESS",
    GET_NOTI_PAGINATION_FAILED: "GET_NOTI_PAGINATION_FAILED",
  },
  SET_READ_NOTI: {
    SET_READ_NOTI: "SET_READ_NOTI",
    SET_READ_NOTI_SUCCESS: "SET_READ_NOTI_SUCCESS",
    SET_READ_NOTI_FAILED: "SET_READ_NOTI_FAILED",
  },
};
