export const ACTION_NAMES = {
  GET_ORDER_PAGINATION: {
    GET_ORDER_PAGINATION: "GET_ORDER_PAGINATION",
    GET_ORDER_PAGINATION_SUCCESS: "GET_ORDER_PAGINATION_SUCCESS",
    GET_ORDER_PAGINATION_FAIL: "GET_ORDER_PAGINATION_FAIL",
  },
  GET_DETAIL: {
    GET_DETAIL: "GET_DETAIL",
    GET_DETAIL_SUCCESS: "GET_DETAIL_SUCCESS",
    GET_DETAIL_FAIL: "GET_DETAIL_FAIL",
  },
  DELETE: {
    DELETE: "DELETE",
    DELETE_SUCCESS: "DELETE_SUCCESS",
    DELETE_FAIL: "DELETE_FAIL",
  },
  EDIT: {
    EDIT: "EDIT",
    EDIT_SUCCESS: "EDIT_SUCCESS",
    EDIT_FAIL: "EDIT_FAIL",
  },
};
