export const ACTION_NAMES = {
  GET_ORDER_PAGINATION: {
    GET_ORDER_PAGINATION: "GET_ORDER_PAGINATION",
    GET_ORDER_PAGINATION_SUCCESS: "GET_ORDER_PAGINATION_SUCCESS",
    GET_ORDER_PAGINATION_FAIL: "GET_ORDER_PAGINATION_FAIL",
  },
  GET_DETAIL_ORDER: {
    GET_DETAIL: "GET_DETAIL",
    GET_DETAIL_SUCCESS: "GET_DETAIL_SUCCESS",
    GET_DETAIL_FAIL: "GET_DETAIL_FAIL",
  },
  DELETE_ORDER: {
    DELETE: "DELETE",
    DELETE_SUCCESS: "DELETE_SUCCESS",
    DELETE_FAIL: "DELETE_FAIL",
  },
  EDIT_ORDER: {
    EDIT: "EDIT",
    EDIT_SUCCESS: "EDIT_SUCCESS",
    EDIT_FAIL: "EDIT_FAIL",
  },
  CANCEL_ORDER: {
    CANCEL_ORDER: "CANCEL_ORDER",
    CANCEL_ORDER_SUCCESS: "CANCEL_ORDER_SUCCESS",
    CANCEL_ORDER_FAIL: "CANCEL_ORDER_FAIL",
  },
  UPDATE_ORDER: {
    UPDATE_ORDER_NOTE: "UPDATE_ORDER_NOTE",
    UPDATE_ORDER_NOTE_SUCCESS: "UPDATE_ORDER_NOTE_SUCCESS",
    UPDATE_ORDER_NOTE_FAIL: "UPDATE_ORDER_NOTE_FAIL",
  },
};
