export const ACTION_NAMES = {
  GET_ORDER_PAGINATION: {
    GET_ORDER_PAGINATION: "GET_ORDER_PAGINATION",
    GET_ORDER_PAGINATION_SUCCESS: "GET_ORDER_PAGINATION_SUCCESS",
    GET_ORDER_PAGINATION_FAIL: "GET_ORDER_PAGINATION_FAIL",
  },
};
