export const NAME_ACTIONS = {
  PAGE_CART: {
    GET_ALL_ITEMS: "GET_ALL_ITEMS",
    GET_ALL_ITEMS_SUCCESS:"GET_ALL_ITEMS_SUCCESS",
    GET_ALL_ITEMS_FAIL:"GET_ALL_ITEMS_FAIL",
  },
  ADD_OR_UPDATE_ITEM: {
    ADD_OR_UPDATE_ITEM_REQUEST: "ADD_OR_UPDATE_ITEM_REQUEST",
    ADD_OR_UPDATE_ITEM_SUCCESS: "ADD_OR_UPDATE_ITEM_SUCCESS",
    ADD_OR_UPDATE_ITEM_FAIL: "ADD_OR_UPDATE_ITEM_FAIL",
  }
};
