export const NAME_ACTIONS = {
  PAGE_CART: {
    GET_ALL_ITEMS: "GET_ALL_ITEMS",
    GET_ALL_ITEMS_SUCCESS: "GET_ALL_ITEMS_SUCCESS",
    GET_ALL_ITEMS_FAIL: "GET_ALL_ITEMS_FAIL",
  },
  ADD_OR_UPDATE_ITEM: {
    ADD_OR_UPDATE_ITEM_REQUEST: "ADD_OR_UPDATE_ITEM_REQUEST",
    ADD_OR_UPDATE_ITEM_SUCCESS: "ADD_OR_UPDATE_ITEM_SUCCESS",
    ADD_OR_UPDATE_ITEM_FAIL: "ADD_OR_UPDATE_ITEM_FAIL",
  },
  UPDATE_ITEM_IN_STATE: {
    UPDATE_ITEM_IN_STATE: "UPDATE_ITEM_IN_STATE",
  },
  DELETE_ITEM: {
    DELETE_ITEM: "DELETE_ITEM",
    DELETE_ITEM_SUCCESS: "DELETE_ITEM_SUCCESS",
    DELETE_ITEM_FAIL: "DELETE_ITEM_FAIL",
  },
  SET_ITEM_TO_CHECK_OUT: {
    SET_ITEM_TO_CHECK_OUT: "SET_ITEM_TO_CHECK_OUT",
    SET_LIST_ITEM_TO_CHECK_OUT: "SET_LIST_ITEM_TO_CHECK_OUT",
    SET_ALL_ITEM_TO_CHECK_OUT: "SET_ALL_ITEM_TO_CHECK_OUT",
  },
};
