export const ACTION_NAMES = {
  GET_PRODUCT_PAGINATION: {
    GET_PRODUCT_PAGINATION: "GET_PRODUCT_PAGINATION",
    GET_PRODUCT_PAGINATION_SUCCESS: "GET_PRODUCT_PAGINATION_SUCCESS",
    GET_PRODUCT_PAGINATION_FAIL: "GET_PRODUCT_PAGINATION_FAIL",
  },
  GET_PRODUCT_DETAIL: {
    GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL",
    GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
    GET_PRODUCT_DETAIL_FAIL: "GET_PRODUCT_DETAIL_FAIL",
  },
  DELETE_PRODUCT: {
    DELETE_PRODUCT: " DELETE_PRODUCT",
    DELETE_PRODUCT_SUCCESS: " DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_FAIL: " DELETE_PRODUCT_FAIL",
  },
  EDIT_PRODUCT: {
    EDIT_PRODUCT: "EDIT_PRODUCT",
    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_FAIL: "EDIT_PRODUCT_FAIL",
  },
  IMPORT: {
    IMPORT: "IMPORT",
    IMPORT_SUCCESS: "IMPORT_SUCCESS",
    IMPORT_FAILED: "IMPORT_FAILED",
    IMPORT_FINALLY: "IMPORT_FINALLY",
  },
};
