export const ACTION_NAMES = {
    GET_PRODUCT_PAGINATION: {
      GET_PRODUCT_PAGINATION: "GET_PRODUCT_PAGINATION",
      GET_PRODUCT_PAGINATION_SUCCESS: "GET_PRODUCT_PAGINATION_SUCCESS",
      GET_PRODUCT_PAGINATION_FAIL: "GET_PRODUCT_PAGINATION_FAIL",
    },
    GET_PRODUCT_DETAIL: {
      GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL",
      GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
      GET_PRODUCT_DETAIL_FAIL: "GET_PRODUCT_DETAIL_FAIL",
    },
  };
  