export const NAME_ACTIONS = {
  GET_SHOP_LOCATION: {
    GET_SHOP_LOCATION: "GET_SHOP_LOCATION",
    GET_SHOP_LOCATION_SUCCESS: "GET_SHOP_LOCATION_SUCCESS",
    GET_SHOP_LOCATION_FINALLY: "GET_SHOP_LOCATION_FINALLY",
  },
};
