export const NAME_ACTIONS = {
  CREATE_ORDER: {
    CREATE_ORDER: "CREATE_ORDER",
    CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",
  },
  CREATE_DELIVERY_FOR_ORDER: {
    CREATE_DELIVERY_FOR_ORDER: "CREATE_DELIVERY_FOR_ORDER",
    CREATE_DELIVERY_FOR_ORDER_SUCCESS: "CREATE_DELIVERY_FOR_ORDER_SUCCESS",
    CREATE_DELIVERY_FOR_ORDER_FAIL: "CREATE_DELIVERY_FOR_ORDER_FAIL",
  },
  GET_FEE: {
    GET_FEE: "GET_FEE",
    GET_FEE_SUCCESS: "GET_FEE_SUCCESS",
    GET_FEE_FAIL: "GET_FEE_FAIL",
  },
  CHECKOUT_ALL: {
    CHECKOUT_ALL: "CHECKOUT_ALL",
  },
  GET_ORDER_PAGINATION: {
    GET_ORDER_PAGINATION: "GET_ORDER_PAGINATION",
    GET_ORDER_PAGINATION_SUCCESS: "GET_ORDER_PAGINATION_SUCCESS",
    GET_ORDER_PAGINATION_FAIL: "GET_ORDER_PAGINATION_FAIL",
  },
  GET_PLACE_ORDER: {
    GET_PLACE_ORDER: "GET_PLACE_ORDER",
  },
  CHECKOUT: {
    CLEAR_ORDER_STATE: "CLEAR_ORDER_STATE",
  },
};
