export const NAME_ACTIONS = {
  CREATE_ORDER: {
    CREATE_ORDER: "CREATE_ORDER",
    CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",
  },
  CREATE_DELIVERY_FOR_ORDER: {
    CREATE_DELIVERY_FOR_ORDER: "CREATE_DELIVERY_FOR_ORDER",
    CREATE_DELIVERY_FOR_ORDER_SUCCESS: "CREATE_DELIVERY_FOR_ORDER_SUCCESS",
    CREATE_DELIVERY_FOR_ORDER_FAIL: "CREATE_DELIVERY_FOR_ORDER_FAIL",
  },
};
