export interface Detail {
    id: string,
    name: string,
    shortDescription: string,
    description: string,
    price: number,
    salePrice: number,
    stockStatus: number,
    totalStock: number,
    viewCount: number,
    media: [],
    authorId: string,
    authorName: string,
    attribute: string,
    language: string,
    dimensions: string,
    publicationDate: string,
    publisher: string,
    publicationCountry: string
}