export const booksContant = {
  GET_MOST_VIEW_REQUEST: "BOOK_MOST_VIEW_REQUEST",
  GET_MOST_VIEW_SUCCESS: "BOOK_MOST_VIEW_SUCCESS",
  GET_MOST_VIEW_FAIL: "BOOK_MOST_VIEW_FAIL",

  GET_ON_SALE_REQUEST: "BOOK_ON_SALE_REQUEST",
  GET_ON_SALE_SUCCESS: "BOOK_ON_SALE_SUCCESS",
  GET_ON_SALE_FAIL: "BOOK_ON_SALE_FAIL",

  GET_DEAL_OF_WEEK_REQUEST: "BOOK_DEAL_OF_WEEK_REQUEST",
  GET_DEAL_OF_WEEK_SUCCESS: "BOOK_DEAL_OF_WEEK_SUCCESS",
  GET_DEAL_OF_WEEK_FAIL: "BOOK_DEAL_OF_WEEK_FAIL",

  GET_BOOKS_FOR_SALE: {
    GET_BOOKS_FOR_SALE: "GET_BOOKS_FOR_SALE",
    GET_BOOKS_FOR_SALE_SUCCESS: "GET_BOOKS_FOR_SALE_SUCCESS",
    GET_BOOKS_FOR_SALE_FAIL: "GET_BOOKS_FOR_SALE_FAIL",
  },

  GET_NEW_RELEASES: {
    GET_NEW_RELEASES: "GET_NEW_RELEASES",
    GET_NEW_RELEASES_SUCCESS: "GET_NEW_RELEASES_SUCCESS",
    GET_NEW_RELEASES_FAIL: "GET_NEW_RELEASES_FAIL",
  },
  GET_BEST_SELLING: {
    GET_BEST_SELLING: "GET_BEST_SELLING",
    GET_BEST_SELLING_SUCCESS: "GET_BEST_SELLING_SUCCESS",
    GET_BEST_SELLING_FAIL: "GET_BEST_SELLING_FAIL",
  },
};
