export const booksContant = {
    GET_MOST_VIEW_REQUEST: 'BOOK_MOST_VIEW_REQUEST',
    GET_MOST_VIEW_SUCCESS: 'BOOK_MOST_VIEW_SUCCESS',
    GET_MOST_VIEW_FAIL: 'BOOK_MOST_VIEW_FAIL',

    GET_ON_SALE_REQUEST: 'BOOK_ON_SALE_REQUEST',
    GET_ON_SALE_SUCCESS: 'BOOK_ON_SALE_SUCCESS',
    GET_ON_SALE_FAIL: 'BOOK_ON_SALE_FAIL',
}