export const NAME_ACTIONS = {
  GET_ALL_AUTHOR: {
    GET_ALL: "GET_ALL",
    GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
    GET_ALL_FAIL: "GET_ALL_FAIL",
  },
  GET_AUTHORS_PAGINATION: {
    GET_AUTHORS_PAGINATION: "GET_AUTHORS_PAGINATION",
    GET_AUTHORS_PAGINATION_SUCCESS: "GET_AUTHORS_PAGINATION_SUCCESS",
  },
};
