export const ACTION_NAMES = {
  LIST: {
    GET_LIST: "GET_LIST",
    GET_LIST_SUCCESS: "GET_LIST_SUCCESS",
    GET_LIST_FAILED: "GET_LIST_FAILED",
  },
  UPSERT: {
    UPSERT_AUTHOR: "UPSERT_AUTHOR",
    UPSERT_AUTHOR_SUCCESS: "UPSERT_AUTHOR_SUCCESS",
    UPSERT_AUTHOR_FAILED: "UPSERT_AUTHOR_FAILED",
  },
  DETAIL: {
    DETAIL: "DETAIL",
    DETAIL_SUCCESS: "DETAIL_SUCCESS",
    DETAIL_FAILED: "DETAIL_FAILED",
  },
};
