export const ACTION_NAMES = {
  CREATE_CATEGORY: {
    CREATE_CATEGORY: "CREATE_CATEGORY",
    CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
    CREATE_CATEGORY_FAIL: "CREATE_CATEGORY_FAIL",
  },
  GET_PAGINATION: {
    GET_PAGINATION: "GET_PAGINATION",
    GET_PAGINATION_SUCCESS: "GET_PAGINATION_SUCCESS",
    GET_PAGINATION_FAIL: "GET_PAGINATION_FAIL",
  },
  RESET_PAGINATION_TO_RELOAD: {
    RESET_PAGINATION_TO_RELOAD: "RESET_PAGINATION_TO_RELOAD",
  },
  GET_CATEGORIES: {
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAIL: "GET_CATEGORIES_FAIL",
  },
};
