export const reviewConstants = {
    GET_REQUEST: 'REVIEWS_GET_REQUEST',
    GET_SUCCESS: 'REVIEWS_GET_SUCCESS',
    GET_FAILURE: 'REVIEW_GET_FAILURE',

    ADD_REQUEST: 'REVIEWS_ADD_REQUEST',
    ADD_SUCCESS: 'REVIEWS_ADD_SUCCESS',
    ADD_FAILURE: 'REVIEW_ADD_FAILURE',
}   