export const NAME_ACTIONS = {
  SIDEBAR: {
    GET_ROOT_CATEGORY: "GET_ROOT_CATEGORY",
    GET_ROOT_SUCCESS: "GET_ROOT_SUCCESS",
    GET_ROOT_FAIL: "GET_ROOT_FAIL",
    GET_SUB_CATEGORY: "GET_SUB_CATEGORY",
    GET_SUB_SUCCESS: "GET_SUB_SUCCESS",
    GET_SUB_FAIL: "GET_SUB_FAIL",
    REFRESH_SIDEBAR: "REFRESH_SIDEBAR",
  },
  GET_CATEGORIES: {
    GET_CATEGORIES: "GET_CATEGORIES",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAIL: "GET_CATEGORIES_FAIL",
  },
};
