export const ACTION_NAMES = {
    ADD_PHOTO: {
        ADD_PHOTO : "ADD_PHOTO",
        ADD_PHOTO_SUCCESS: "ADD_PHOTO_SUCCESS",
        ADD_PHOTO_FAIL: "ADD_PHOTO_FAIL"
    },
    DELETE_PHOTO: {
        DELETE_PHOTO : "DELETE_PHOTO",
        DELETE_PHOTO_SUCCESS: "DELETE_PHOTO_SUCCESS",
        DELETE_PHOTO_FAIL: "DELETE_PHOTO_FAIL"
    }
}