export const ACTION_NAMES = {
  GET_ALL: {
    GET_NOTI_PAGINATION: "GET_NOTI_PAGINATION",
    GET_NOTI_PAGINATION_SUCCESS: "GET_NOTI_PAGINATION_SUCCESS",
    GET_NOTI_PAGINATION_FAILED: "GET_NOTI_PAGINATION_FAILED",
  },
  SET_READ_NOTI: {
    SET_READ_NOTI: "SET_READ_NOTI",
    SET_READ_NOTI_SUCCESS: "SET_READ_NOTI_SUCCESS",
    SET_READ_NOTI_FAILED: "SET_READ_NOTI_FAILED",
  },
  CATCH_NEW_NOTI: "CATCH_NEW_NOTI",
  SEND_TO_USERS: {
    SEND_TO_USERS: "SEND_TO_USERS",
    SEND_TO_USERS_SUCCESS: "SEND_TO_USERS_SUCCESS",
    SEND_TO_USERS_FINALLY: "SEND_TO_USERS_FINALLY",
  },
  ADMIN_GET_ALL_NOTI: {
    ADMIN_GET_NOTI_PAGINATION: "ADMIN_GET_NOTI_PAGINATION",
    ADMIN_GET_NOTI_PAGINATION_SUCCESS: "ADMIN_GET_NOTI_PAGINATION_SUCCESS",
    ADMIN_GET_NOTI_PAGINATION_FAILED: "ADMIN_GET_NOTI_PAGINATION_FAILED",
  },
};
