export const ACTION_NAMES = {
  GET_ALL_SETTINGS: {
    GET_ALL: "GET_ALL",
    GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
    GET_ALL_FAIL: "GET_ALL_FAIL",
  },
  UPDATE_SETTINGS: {
    UPDATE: "UPDATE",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    UPDATE_FAIL: "UPDATE_FAIL",
  },
};
